// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: proto/auth.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export enum FriendStatus {
  PENDING = 0,
  ACCEPTED = 1,
  BLOCKED = 2,
  UNRECOGNIZED = -1,
}

/** --- Register/Login/OTP/Refresh  --- */
export interface RegisterRequest {
  username: string;
  password: string;
  email: string;
  realname: string;
}

export interface RegisterResponse {
  success: boolean;
  auth_id: number;
}

export interface LoginRequest {
  username: string;
  password: string;
}

export interface LoginResponse {
  sessionId: string;
}

export interface VerifyOtpRequest {
  sessionId: string;
  otp: string;
}

export interface VerifyOtpResponse {
  access_token: string;
  refresh_token: string;
  auth_id: number;
  role: string;
}

export interface RefreshRequest {
  refreshToken: string;
}

export interface RefreshResponse {
  access_token: string;
  refresh_token: string;
}

/** --- User methods --- */
export interface ChangePasswordRequest {
  sessionId: string;
  oldPassword: string;
  newPassword: string;
}

export interface ChangePasswordResponse {
  success: boolean;
}

export interface ResetPasswordRequest {
  username: string;
  otp: string;
  newPassword: string;
}

export interface ResetPasswordResponse {
  success: boolean;
}

export interface ChangeEmailRequest {
  sessionId: string;
  newEmail: string;
}

export interface ChangeEmailResponse {
  success: boolean;
}

/** --- Admin methods --- */
export interface ChangeRoleRequest {
  /** user target */
  username: string;
  newRole: string;
}

export interface ChangeRoleResponse {
  success: boolean;
}

export interface BanUserRequest {
  username: string;
}

export interface BanUserResponse {
  success: boolean;
}

export interface UnbanUserRequest {
  username: string;
}

export interface UnbanUserResponse {
  success: boolean;
}

/** --- Request OTP reset password --- */
export interface RequestResetPasswordRequest {
  username: string;
}

export interface RequestResetPasswordResponse {
  success: boolean;
}

export interface ChangeRolePartnerRequest {
  username: string;
}

export interface ChangeRolePartnerResponse {
  success: boolean;
}

export interface GetEmailUserRequest {
  id: number;
}

export interface GetEmailUserResponse {
  email: string;
}

export interface GetProfileRequest {
  id: number;
}

export interface GetProfileReponse {
  role: string;
  biBan: boolean;
  avatarUrl: string;
}

export interface SendEmailToUserRequest {
  who: string;
  title: string;
  content: string;
}

export interface SendemailToUserResponse {
  success: boolean;
}

export interface ChangeAvatarRequest {
  userId: number;
  avatarUrl: string;
}

export interface ChangeAvatarResponse {
  success: boolean;
}

export interface RelationFriendInfo {
  relationId: number;
  friendId: number;
  friendRealname: string;
  avatarUrl: string;
  status: FriendStatus;
  create_at: string;
}

export interface FriendInfo {
  friendId: number;
  friendRealname: string;
  avatarUrl: string;
  status: FriendStatus;
}

export interface AddFriendRequest {
  userId: number;
  friendId: number;
}

export interface AddFriendResponse {
  relationId: number;
  userId: number;
  friendId: number;
  status: FriendStatus;
  create_at: string;
}

export interface GetSentFriendRequest {
  userId: number;
}

export interface GetSentFriendResponse {
  relationFriendInfo: RelationFriendInfo[];
}

export interface GetIncomingFriendRequest {
  userId: number;
}

export interface GetIncomingFriendResponse {
  relationFriendInfo: RelationFriendInfo[];
}

export interface AcceptFriendRequest {
  relationId: number;
}

export interface AcceptFriendResponse {
  relationFriendInfo: RelationFriendInfo | undefined;
}

export interface RejectFriendRequest {
  relationId: number;
}

export interface RejectFriendResponse {
  success: boolean;
}

export interface GetAllFriendRequest {
  userId: number;
}

export interface GetAllFriendResponse {
  friendInfo: FriendInfo[];
}

export interface UnfriendRequest {
  userId: number;
  friendId: number;
}

export interface UnfriendResponse {
  success: boolean;
}

export interface BlockUserRequest {
  userId: number;
  friendId: number;
}

export interface BlockUserResponse {
  success: boolean;
}

export const AUTH_PACKAGE_NAME = "auth";

/** ===== SERVICE DEFINITION ===== */

export interface AuthServiceClient {
  /** user actions */

  register(request: RegisterRequest, metadata?: Metadata): Observable<RegisterResponse>;

  login(request: LoginRequest, metadata?: Metadata): Observable<LoginResponse>;

  verifyOtp(request: VerifyOtpRequest, metadata?: Metadata): Observable<VerifyOtpResponse>;

  refresh(request: RefreshRequest, metadata?: Metadata): Observable<RefreshResponse>;

  changePassword(request: ChangePasswordRequest, metadata?: Metadata): Observable<ChangePasswordResponse>;

  resetPassword(request: ResetPasswordRequest, metadata?: Metadata): Observable<ResetPasswordResponse>;

  requestResetPassword(
    request: RequestResetPasswordRequest,
    metadata?: Metadata,
  ): Observable<RequestResetPasswordResponse>;

  changeEmail(request: ChangeEmailRequest, metadata?: Metadata): Observable<ChangeEmailResponse>;

  changeRolePartner(request: ChangeRolePartnerRequest, metadata?: Metadata): Observable<ChangeRolePartnerResponse>;

  getEmailUser(request: GetEmailUserRequest, metadata?: Metadata): Observable<GetEmailUserResponse>;

  getProfile(request: GetProfileRequest, metadata?: Metadata): Observable<GetProfileReponse>;

  changeAvatar(request: ChangeAvatarRequest, metadata?: Metadata): Observable<ChangeAvatarResponse>;

  /** admin actions */

  changeRole(request: ChangeRoleRequest, metadata?: Metadata): Observable<ChangeRoleResponse>;

  banUser(request: BanUserRequest, metadata?: Metadata): Observable<BanUserResponse>;

  unbanUser(request: UnbanUserRequest, metadata?: Metadata): Observable<UnbanUserResponse>;

  sendEmailToUser(request: SendEmailToUserRequest, metadata?: Metadata): Observable<SendemailToUserResponse>;

  /** admin service gọi khi check account có đủ điều kiện đăng bán không */

  checkAccount(request: LoginRequest, metadata?: Metadata): Observable<LoginResponse>;

  /** Gửi lời mời kết bạn ( Người gửi ) */

  addFriend(request: AddFriendRequest, metadata?: Metadata): Observable<AddFriendResponse>;

  /** Xem tất cả lời mời kết bạn mà bản thân đã gửi ( Người gửi ) */

  getSentFriend(request: GetSentFriendRequest, metadata?: Metadata): Observable<GetSentFriendResponse>;

  /** Xem tất cả lời mời kết bạn của bản thân để accept ( Người nhận ) */

  getIncomingFriend(request: GetIncomingFriendRequest, metadata?: Metadata): Observable<GetIncomingFriendResponse>;

  /** Chấp nhận yêu cầu kết bạn ( Người nhận ) */

  acceptFriend(request: AcceptFriendRequest, metadata?: Metadata): Observable<AcceptFriendResponse>;

  /** Hủy yêu cầu kết bạn ( chỉ áp dụng khi pending ) ( xóa record ) ( Người nhận ) */

  rejectFriend(request: RejectFriendRequest, metadata?: Metadata): Observable<RejectFriendResponse>;

  /** Lấy danh sách bạn bè của bản thân */

  getAllFriend(request: GetAllFriendRequest, metadata?: Metadata): Observable<GetAllFriendResponse>;

  /** Xóa 1 bạn bè nhất định ( xóa record ) */

  unfriend(request: UnfriendRequest, metadata?: Metadata): Observable<UnfriendResponse>;

  /** Chặn bạn bè bất kì ( Blocking User ) */

  blockUser(request: BlockUserRequest, metadata?: Metadata): Observable<BlockUserResponse>;
}

/** ===== SERVICE DEFINITION ===== */

export interface AuthServiceController {
  /** user actions */

  register(request: RegisterRequest, metadata?: Metadata): Observable<RegisterResponse>;

  login(request: LoginRequest, metadata?: Metadata): Observable<LoginResponse>;

  verifyOtp(request: VerifyOtpRequest, metadata?: Metadata): Observable<VerifyOtpResponse>;

  refresh(request: RefreshRequest, metadata?: Metadata): Observable<RefreshResponse>;

  changePassword(request: ChangePasswordRequest, metadata?: Metadata): Observable<ChangePasswordResponse>;

  resetPassword(request: ResetPasswordRequest, metadata?: Metadata): Observable<ResetPasswordResponse>;

  requestResetPassword(
    request: RequestResetPasswordRequest,
    metadata?: Metadata,
  ): Observable<RequestResetPasswordResponse>;

  changeEmail(request: ChangeEmailRequest, metadata?: Metadata): Observable<ChangeEmailResponse>;

  changeRolePartner(request: ChangeRolePartnerRequest, metadata?: Metadata): Observable<ChangeRolePartnerResponse>;

  getEmailUser(request: GetEmailUserRequest, metadata?: Metadata): Observable<GetEmailUserResponse>;

  getProfile(request: GetProfileRequest, metadata?: Metadata): Observable<GetProfileReponse>;

  changeAvatar(request: ChangeAvatarRequest, metadata?: Metadata): Observable<ChangeAvatarResponse>;

  /** admin actions */

  changeRole(request: ChangeRoleRequest, metadata?: Metadata): Observable<ChangeRoleResponse>;

  banUser(request: BanUserRequest, metadata?: Metadata): Observable<BanUserResponse>;

  unbanUser(request: UnbanUserRequest, metadata?: Metadata): Observable<UnbanUserResponse>;

  sendEmailToUser(request: SendEmailToUserRequest, metadata?: Metadata): Observable<SendemailToUserResponse>;

  /** admin service gọi khi check account có đủ điều kiện đăng bán không */

  checkAccount(request: LoginRequest, metadata?: Metadata): Observable<LoginResponse>;

  /** Gửi lời mời kết bạn ( Người gửi ) */

  addFriend(request: AddFriendRequest, metadata?: Metadata): Observable<AddFriendResponse>;

  /** Xem tất cả lời mời kết bạn mà bản thân đã gửi ( Người gửi ) */

  getSentFriend(request: GetSentFriendRequest, metadata?: Metadata): Observable<GetSentFriendResponse>;

  /** Xem tất cả lời mời kết bạn của bản thân để accept ( Người nhận ) */

  getIncomingFriend(request: GetIncomingFriendRequest, metadata?: Metadata): Observable<GetIncomingFriendResponse>;

  /** Chấp nhận yêu cầu kết bạn ( Người nhận ) */

  acceptFriend(request: AcceptFriendRequest, metadata?: Metadata): Observable<AcceptFriendResponse>;

  /** Hủy yêu cầu kết bạn ( chỉ áp dụng khi pending ) ( xóa record ) ( Người nhận ) */

  rejectFriend(request: RejectFriendRequest, metadata?: Metadata): Observable<RejectFriendResponse>;

  /** Lấy danh sách bạn bè của bản thân */

  getAllFriend(request: GetAllFriendRequest, metadata?: Metadata): Observable<GetAllFriendResponse>;

  /** Xóa 1 bạn bè nhất định ( xóa record ) */

  unfriend(request: UnfriendRequest, metadata?: Metadata): Observable<UnfriendResponse>;

  /** Chặn bạn bè bất kì ( Blocking User ) */

  blockUser(request: BlockUserRequest, metadata?: Metadata): Observable<BlockUserResponse>;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "register",
      "login",
      "verifyOtp",
      "refresh",
      "changePassword",
      "resetPassword",
      "requestResetPassword",
      "changeEmail",
      "changeRolePartner",
      "getEmailUser",
      "getProfile",
      "changeAvatar",
      "changeRole",
      "banUser",
      "unbanUser",
      "sendEmailToUser",
      "checkAccount",
      "addFriend",
      "getSentFriend",
      "getIncomingFriend",
      "acceptFriend",
      "rejectFriend",
      "getAllFriend",
      "unfriend",
      "blockUser",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
